In [4]:
import imageio
import matplotlib.pyplot as plt
import numpy as np
from haar import *

In [4]:
cam = imageio.imread("imageio:camera.png")
imageio.imsave("cam.png", cam)

cam = imageio.imread("cam.png").astype(float)
xform_cam = fast_2d_haar_transform(cam).astype(np.uint8)

imageio.imsave("cam_xform.png", xform_cam)

xform_cam = inplace_fast_2d_haar_transform(cam).astype(np.uint8)

imageio.imsave("cam_inplace_xform.png", xform_cam)

xform_cam = inplace_inverse_fast_2d_haar_transform(xform_cam).astype(np.uint8)

imageio.imsave("inplace_inverse_cam_xform.png", xform_cam)


In [16]:
# Heavily based on Wavelets Made Easy, Algorithm 1.16
def inplace_fast_1d_haar_transform(signal):
    n = int(log(len(signal), 2))
    s = zero_pad(signal)
    
    I = 1
    J = 2
    M = int(2**n)
    
    for L in range(1, n+1):
        M = M//2
        for K in range(M):
            a = (s[J*K] + s[J*K+I]) / 2
            c = (s[J*K] - s[J*K+I]) / 2
            s[J*K] = a
            s[J*K+I] = c
        print(s)
        I = J
        J = 2*J
        
    return s

# Heavily based on Wavelets Made Easy, Algorithm 1.19
def inplace_inverse_fast_1d_haar_transform(signal):
    n = int(log(len(signal), 2))
    s = zero_pad(signal)
    
    I = int(2**(n-1))
    J = 2*I
    M = 1
    
    for L in range(n+1, 1, -1):
        for K in range(M):
            a1 = s[J*K] + s[J*K+I]
            a2 = s[J*K] - s[J*K+I]
            s[J*K] = a1
            s[J*K+I] = a2
        J = I
        I = I//2
        M = 2*M

    return s

def inplace_fast_2d_haar_transform(matrix):
    first_transform = np.array([inplace_fast_1d_haar_transform(row) for row in matrix])
    second_transform_T = [inplace_fast_1d_haar_transform(col) for col in first_transform.T]
    return np.array(second_transform_T).T


In [17]:
signal = [5, 1, 2, 8]
haar_signal = inplace_fast_1d_haar_transform(signal)
print(haar_signal)
print(inplace_inverse_fast_1d_haar_transform(haar_signal))

[3.0, 2.0, 5.0, -3.0]
[4.0, 2.0, -1.0, -3.0]
[4.0, 2.0, -1.0, -3.0]
[5.0, 1.0, 2.0, 8.0]


In [18]:
signal = [9, 7, 6, 2]
haar_signal = inplace_fast_1d_haar_transform(signal)
print(haar_signal)
print(inplace_inverse_fast_1d_haar_transform(haar_signal))

[8.0, 1.0, 4.0, 2.0]
[6.0, 1.0, 2.0, 2.0]
[6.0, 1.0, 2.0, 2.0]
[9.0, 7.0, 6.0, 2.0]


In [15]:
signal = [5, 1, 2, 8]
haar_signal = fast_1d_haar_transform(signal)
print(haar_signal)
print(inverse_fast_1d_haar_transform(haar_signal))

[3.0, 5.0, 2.0, -3.0]
[4.0, -1.0, 2.0, -3.0]
[4.0, -1.0, 2.0, -3.0]


NameError: name 'inverse_fast_1d_haar_transform' is not defined

In [9]:
signal = [9, 7, 6, 2]
haar_signal = fast_1d_haar_transform(signal)
print(haar_signal)
print(inverse_fast_1d_haar_transform(haar_signal))

[6.0, 2.0, 1.0, 2.0]


NameError: name 'inverse_fast_1d_haar_transform' is not defined

In [5]:
signal = [3, 1, 0, 4, 8, 6, 9, 9]
haar_signal = inplace_fast_1d_haar_transform(signal)
print(haar_signal)
print(inplace_inverse_fast_1d_haar_transform(haar_signal))

[5.0, 1.0, 0.0, -2.0, -3.0, 1.0, -1.0, 0.0]
[3.0, 1.0, 0.0, 4.0, 8.0, 6.0, 9.0, 9.0]


In [6]:
signal = [9, 7, 3, 5, 6, 10, 2, 6]
haar_signal = inplace_fast_1d_haar_transform(signal)
print(haar_signal)
print(inplace_inverse_fast_1d_haar_transform(haar_signal))

[6.0, 1.0, 2.0, -1.0, 0.0, -2.0, 2.0, -2.0]
[9.0, 7.0, 3.0, 5.0, 6.0, 10.0, 2.0, 6.0]


In [11]:
signal = [3, 1, 0, 4, 8, 6, 9, 9]
haar_signal = fast_1d_haar_transform(signal)
print(haar_signal)
print(inverse_fast_1d_haar_transform(haar_signal))

[5.0, -3.0, 0.0, -1.0, 1.0, -2.0, 1.0, 0.0]


NameError: name 'inverse_fast_1d_haar_transform' is not defined

In [7]:
signal = [9, 7, 3, 5, 6, 10, 2, 6]
haar_signal = fast_1d_haar_transform(signal)
print(haar_signal)
print(inverse_fast_1d_haar_transform(haar_signal))

[6.0, 0.0, 2.0, 2.0, 1.0, -1.0, -2.0, -2.0]


NameError: name 'inverse_fast_1d_haar_transform' is not defined

In [28]:
"""
https://wiki.python.org/moin/NumericAndScientificRecipes
Find 2^n that is equal to or greater than.
"""
def nextpow2(i):
    n = 1
    while n < i: n *= 2
    return n

"""
https://www.mathworks.com/matlabcentral/fileexchange/45247-code-for-generating-haar-matrix?fbclid=IwAR3iNpupw8mx7l763E8RDpyQdkmj7TGKOpJAs3FMfTCRa0Fh85AAQ_aUbV0
Input: N must be a power of 2
Output: NxN Haar matrix
"""
def generate_haar_matrix(N):
    p = [0, 0]
    q = [0, 1]
    n = nextpow2(N)
    
    for i in range(1, n-2):
        p.extend(2**i*[i])
        t = list(range(1, 2**i+1))
        q.extend(t)

    Hr = [[0 for _ in range(N)] for _ in range(N)]
    Hr[0][:] = N*[1]

    for i in range(1, N):
        P = p[i]
        Q = q[i]
        for j in range(int((N*(Q-1)/(2**P))), int(N*((Q-0.5)/(2**P)))):
            Hr[i][j] = 2**(P/2)
        for j in range(int(N*((Q-0.5)/(2**P))), int(N*(Q/(2**P)))):
            Hr[i][j] = -(2**(P/2))
            
#     print(Hr)
    Hr = [[i*(N**-.5) for i in j] for j in Hr]
#     print(Hr)
    return Hr

In [29]:
print(haar_matrix(2))
print(generate_haar_matrix(4))

[[ 1.  1.  1.  1.]
 [ 1.  1. -1. -1.]
 [ 1. -1.  0. -0.]
 [ 0. -0.  1. -1.]]
[[0.5, 0.5, 0.5, 0.5], [0.5, 0.5, -0.5, -0.5], [0.7071067811865476, -0.7071067811865476, 0.0, 0.0], [0.0, 0.0, 0.7071067811865476, -0.7071067811865476]]


In [74]:
print(list(range(1,10)))

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
# inplace_inverse_fast_1d_haar_transform

def fast_2d_haar_transform(matrix, N):
    if N == 1:
        return
    first_transform = np.array([inplace_fast_1d_haar_transform(row) for row in matrix[0:2**N-1][0:2**N-1]])
    second_transform = [inplace_fast_1d_haar_transform(col) for col in first_transform.T].T
    third_transform = 
    rearrange matrix
    2d_haar_transform(matrix[0:2**N-1][0:2**N-1], N/2)