In [1]:
# Import external libraries
import numpy as np
# import pywt - will eventually test against PyWavelets

# Import custom code
from haar import *

In [2]:
# Set up test signals based on Wavelets Made Easy
test_1d_a = np.array([5, 4], dtype=float)
test_1d_b = np.array([5, 1, 2, 8], dtype=float)
test_1d_c = np.array([3, 1, 0, 4, 8, 6, 9, 9], dtype=float)
test_2d_a = np.array([[9, 7], [5, 3]], dtype=float)
test_2d_b = np.array([[9, 7, 6, 2], [5, 3, 4, 4], [8, 2, 4, 0], [6, 0, 2, 2]], dtype=float)

In [3]:
# Run ordered transforms
test_1d_a_ordered = ordered_fast_1d_haar_transform(test_1d_a)
test_1d_b_ordered = ordered_fast_1d_haar_transform(test_1d_b)
test_1d_c_ordered = ordered_fast_1d_haar_transform(test_1d_c)
test_2d_a_ordered = ordered_fast_2d_haar_transform(test_2d_a)
test_2d_b_ordered = ordered_fast_2d_haar_transform(test_2d_b)
print(test_1d_a_ordered)
print(test_1d_b_ordered)
print(test_1d_c_ordered)
print(test_2d_a_ordered)
print(test_2d_b_ordered)

[4.5 0.5]
[ 4. -1.  2. -3.]
[ 5. -3.  0. -1.  1. -2.  1.  0.]
[[6. 1.]
 [2. 0.]]
[[ 4.   1.   2.   1. ]
 [ 1.   0.  -1.   0. ]
 [ 1.   1.   0.   1. ]
 [ 0.5  0.5  0.   1. ]]


In [4]:
# TODO - Run ordered inverse transforms
#test_1d_a_ordered_inverse = ordered_inverse_fast_1d_haar_transform(test_1d_a_ordered)
#test_1d_b_ordered_inverse = ordered_inverse_fast_1d_haar_transform(test_1d_b_ordered)
#test_1d_c_ordered_inverse = ordered_inverse_fast_1d_haar_transform(test_1d_c_ordered)
#test_2d_a_ordered_inverse = ordered_inverse_fast_2d_haar_transform(test_2d_a_ordered)
#test_2d_b_ordered_inverse = ordered_inverse_fast_2d_haar_transform(test_2d_b_ordered)
#print(test_1d_a_ordered_inverse)
#print(test_1d_b_ordered_inverse)
#print(test_1d_c_ordered_inverse)
#print(test_2d_a_ordered_inverse)
#print(test_2d_b_ordered_inverse)

In [5]:
# Run inplace transforms
test_1d_a_inplace = inplace_fast_1d_haar_transform(test_1d_a)
test_1d_b_inplace = inplace_fast_1d_haar_transform(test_1d_b)
test_1d_c_inplace = inplace_fast_1d_haar_transform(test_1d_c)
test_2d_a_inplace = inplace_fast_2d_haar_transform(test_2d_a)
test_2d_b_inplace = inplace_fast_2d_haar_transform(test_2d_b)
print(test_1d_a_inplace)
print(test_1d_b_inplace)
print(test_1d_c_inplace)
print(test_2d_a_inplace)
print(test_2d_b_inplace)

[4.5 0.5]
[ 4.  2. -1. -3.]
[ 5.  1.  0. -2. -3.  1. -1.  0.]
[[6. 1.]
 [2. 0.]]
[[ 4.   2.   1.   1. ]
 [ 1.   0.   1.   1. ]
 [ 1.  -1.   0.   0. ]
 [ 0.5  0.   0.5  1. ]]


In [6]:
# Run inplace inverse transforms
test_1d_a_inplace_inverse = inplace_inverse_fast_1d_haar_transform(test_1d_a_inplace)
test_1d_b_inplace_inverse = inplace_inverse_fast_1d_haar_transform(test_1d_b_inplace)
test_1d_c_inplace_inverse = inplace_inverse_fast_1d_haar_transform(test_1d_c_inplace)
test_2d_a_inplace_inverse = inplace_inverse_fast_2d_haar_transform(test_2d_a_inplace)
test_2d_b_inplace_inverse = inplace_inverse_fast_2d_haar_transform(test_2d_b_inplace)
print(test_1d_a_inplace_inverse)
print(test_1d_b_inplace_inverse)
print(test_1d_c_inplace_inverse)
print(test_2d_a_inplace_inverse)
print(test_2d_b_inplace_inverse)

[5. 4.]
[5. 1. 2. 8.]
[3. 1. 0. 4. 8. 6. 9. 9.]
[[9. 7.]
 [5. 3.]]
[[9. 7. 6. 2.]
 [5. 3. 4. 4.]
 [8. 2. 4. 0.]
 [6. 0. 2. 2.]]


In [7]:
# Run "slow" matrix-based transforms
test_1d_a_matrix = matrix_1d_haar_transform(test_1d_a)
test_1d_b_matrix = matrix_1d_haar_transform(test_1d_b)
test_1d_c_matrix = matrix_1d_haar_transform(test_1d_c)
test_2d_a_matrix = matrix_2d_haar_transform(test_2d_a)
test_2d_b_matrix = matrix_2d_haar_transform(test_2d_b)
print(test_1d_a_matrix)
print(test_1d_b_matrix)
print(test_1d_c_matrix)
print(test_2d_a_matrix)
print(test_2d_b_matrix)

[6.36396103 0.70710678]
[ 4.41421356  1.58578644  7.65685425 -3.65685425]
[ 7.07106781 -4.24264069  5.65685425 -2.82842712  9.07106781 -3.65685425
  5.07106781 -7.65685425]
[[1.20000000e+01 2.00000000e+00]
 [4.00000000e+00 6.66133815e-16]]
[[ 1.60000000e+01  4.00000000e+00  5.65685425e+00  2.82842712e+00]
 [ 4.00000000e+00  0.00000000e+00 -2.82842712e+00  0.00000000e+00]
 [ 2.82842712e+00  2.82842712e+00  6.66133815e-16  2.00000000e+00]
 [ 1.41421356e+00  1.41421356e+00  0.00000000e+00  2.00000000e+00]]


In [13]:
# Run "slow" matrix-based inverse transforms
test_1d_a_matrix_inverse = matrix_1d_haar_transform(test_1d_a_matrix)
test_1d_b_matrix_inverse = matrix_1d_haar_transform(test_1d_b_matrix)
test_1d_c_matrix_inverse = matrix_1d_haar_transform(test_1d_c_matrix)
test_2d_a_matrix_inverse = matrix_2d_haar_transform(test_2d_a_matrix)
test_2d_b_matrix_inverse = matrix_2d_haar_transform(test_2d_b_matrix)
print(test_1d_a_matrix_inverse)
print(test_1d_b_matrix_inverse)
print(test_1d_c_matrix_inverse)
print(test_2d_a_matrix_inverse)
print(test_2d_b_matrix_inverse)

[5. 4.]
[ 8.41421356 -2.41421356 -1.17157288  4.        ]
[10.24264069 -2.58578644 -4.41421356  0.75735931  6.17157288 -1.
  0.         10.82842712]
[[9. 7.]
 [5. 3.]]
[[ 1.05355339e+01  5.70710678e+00  5.65685425e+00 -1.41421356e+00]
 [ 4.29289322e+00  3.46446609e+00  5.65685425e+00  1.41421356e+00]
 [ 9.65685425e+00  1.65685425e+00  4.00000000e+00  2.82842712e+00]
 [ 1.00000000e+00  1.00000000e+00  0.00000000e+00  3.33066907e-16]]
