In [1]:
# Import external libraries
import numpy as np
import pywt

# Import custom code
from haar import *

In [2]:
# Set up test signals based on Wavelets Made Easy
test_1d_a = np.array([5, 4], dtype=float)
test_1d_b = np.array([5, 1, 2, 8], dtype=float)
test_1d_c = np.array([3, 1, 0, 4, 8, 6, 9, 9], dtype=float)
test_2d_a = np.array([[9, 7], [5, 3]], dtype=float)
test_2d_b = np.array([[9, 7, 6, 2], [5, 3, 4, 4], [8, 2, 4, 0], [6, 0, 2, 2]], dtype=float)

In [5]:
# Run ordered transforms
print(ordered_fast_1d_haar_transform(test_1d_a))
print(ordered_fast_1d_haar_transform(test_1d_b))
print(ordered_fast_1d_haar_transform(test_1d_c))
print(ordered_fast_2d_haar_transform(test_2d_a))
print(ordered_fast_2d_haar_transform(test_2d_b))

[4.5 0.5]
[ 4. -1.  2. -3.]
[ 5. -3.  0. -1.  1. -2.  1.  0.]
[[6. 1.]
 [2. 0.]]
[[ 4.   1.   2.   1. ]
 [ 1.   0.  -1.   0. ]
 [ 1.   1.   0.   1. ]
 [ 0.5  0.5  0.   1. ]]


In [21]:
# TODO - run ordered inverse transforms


In [8]:
# Run ordered transform
print(inplace_fast_1d_haar_transform(test_1d_a))
print(inplace_fast_1d_haar_transform(test_1d_b))
print(inplace_fast_1d_haar_transform(test_1d_c))
print(inplace_fast_2d_haar_transform(test_2d_a))
print(inplace_fast_2d_haar_transform(test_2d_b))

[4.5 0.5]
[ 4.  2. -1. -3.]
[ 5.  1.  0. -2. -3.  1. -1.  0.]
[[6. 1.]
 [2. 0.]]
[[ 4.   2.   1.   1. ]
 [ 1.   0.   1.   1. ]
 [ 1.  -1.   0.   0. ]
 [ 0.5  0.   0.5  1. ]]
